print("                        ")
print("        \\\\|||||//     ")
print("        ( o   o )       ")
print("|--ooO-----(_)----------|")
print("|                       |")
print("|     Hello world!      |")
print("|                       |")
print("|------------------Ooo--|")
print("         |__||__|        ")
print("          ||  ||         ")
print("         ooO  Ooo")