name = input("Wat is je naam : ")
lengte = len(name)
print("                        ")
print("        \\\\|||||//     ")
print("        ( o   o )       ")
print("|--ooO-----(_)----------|")
print("|                       |")
print("|     Hello " + name + "!" + (11 - lengte)*" "+ "|")
print("|                       |")
print("|------------------Ooo--|")
print("         |__||__|        ")
print("          ||  ||         ")
print("         ooO  Ooo")